# Generated by Django 4.2.11 on 2025-07-14 11:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Agent rating (0.00-5.00)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience (0-99)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterUniqueTogether(
            name='agentreview',
            unique_together={('agent', 'reviewer_email')},
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['agency_name'], name='agents_agen_agency__c8c5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_verified'], name='agents_agen_is_veri_d1195a_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['rating'], name='agents_agen_rating_a95fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['years_experience'], name='agents_agen_years_e_98408c_idx'),
        ),
    ]
